finchcollector/finchcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

finchcollector/main_app/urls.py
from django.urls import path
from .import views

urlpatterns = [
    #http://localhost:8000
    path('', views.home, name='home'),
    #http://localhost:8000/about/
    path('about/', views.about, name='about'),
     #http://localhost:8000/finches/
    path('finches/', views.finches_index, name='index'),

    path('finches/<int:finch_id>/', views.finches_detail, name='detail'),

    path('finches/create/', views.FinchCreate.as_view(), name='finches_create'),

    path('finches/<int:pk>/update/', views.FinchUpdate.as_view(), name='finches_update'),
    path('finches/<int:pk>/delete/', views.FinchDelete.as_view(), name='finches_delete'),
    path('finches/<int:finch_id>/add_feeding/', views.add_feeding, name='add_feeding'),
    path('finches/<int:finch_id>/assoc_toy/<int:toy_id>/', views.assoc_toy, name='assoc_toy'),
    path('finches/<int:finch_id>/add_photo/', views.add_photo, name='add_photo'),
]

finchcollector/main_app/models.py
from django.db import models
from django.urls import reverse

MEALS = (
    ('B', 'Breakfast'),
    ('L', 'Lunch'),
    ('D', 'Dinner')
)

class Toy(models.Model):
    name = models.CharField(max_length=50)
    color= models.CharField(max_length=20)

    def get_absolute_url(self):
        return reverse('toys_detail', kwargs={'pk': self.id})

    def __str__(self):
        return self.name


class Finch(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    lifespan = models.IntegerField()
    toys = models.ManyToManyField(Toy,blank=True)

    def __str__(self):
        return self.name

class Photo(models.Model):
    url = models.CharField(max_length=200)
    finch = models.ForeignKey(Finch, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for finch_id: {self.finch_id} @{self.url}"


class Feeding(models.Model):
    date = models.DateField("feeding date")
    meal = models.CharField(
        max_length=1,
        choices=MEALS,
        default=MEALS[0][0]
    )

    finch = models.ForeignKey(Finch, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.get_meal_display()} on {self.date}"

    class Meta:
        ordering = ['-date']

finchcollector/main_app/forms.py
from dataclasses import fields
from pyexpat import model
from django.forms import ModelForm
from .models import Feeding

class FeedingForm(ModelForm):
    class Meta:
        model = Feeding
        fields = ['date', 'meal']

finchcollector/main_app/views.py
from django.shortcuts import render, redirect
import os
from django.http import HttpResponse
from django.views.generic.edit import CreateView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Finch, Toy, Photo
from .forms import FeedingForm
import uuid
import boto3
import logging 
logging.basicConfig(level=logging.DEBUG)

from django.db import models

# Create your views here.
def home(request):
    """
    home view
    http://localhost:8000
    """
    return HttpResponse("hello world")

def about(request):
  """
   home view
    http://localhost:8000/about
  """
  return render(request, 'about.html')

def finches_index(request):
  """
   cats index page
    http://localhost:8000/finches
  """
  finches = Finch.objects.all()
  return render(request, 'finches/index.html',{'finches':finches})

def finches_detail(request, finch_id):
  finch = Finch.objects.get(id=finch_id)
  toys_finch_doesnt_have = Toy.objects.exclude(id__in = finch.toys.all().values_list('id'))
  return render(request, 'finches/detail.html', { 'finch': finch, 'feeding_form': FeedingForm, 'toys' : toys_finch_doesnt_have })


def add_feeding(request, finch_id):
    form = FeedingForm(request.POST)
    if form.is_valid():
        new_feeding = form.save(commit=False)
        new_feeding.finch_id = finch_id
        new_feeding.save()
    return redirect('detail', finch_id=finch_id)

def assoc_toy(request, finch_id, toy_id):
  Finch.objects.get(id=finch_id).toys.add(toy_id)
  return redirect('detail', finch_id=finch_id)

def add_photo(request, finch_id):
    # photo-file will be the "name" attribute on the <input type="file">
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        # need a unique "key" for S3 / needs image file extension too
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
        # just in case something goes wrong
        try:
            bucket = os.environ['S3_BUCKET']
            s3.upload_fileobj(photo_file, bucket, key)
            # build the full url string
            url = f"{os.environ['S3_BASE_URL']}{bucket}/{key}"
            Photo.objects.create(url=url, finch_id=finch_id)
        except:
            print('An error occurred uploading file to S3')
    return redirect('detail', finch_id=finch_id)


class FinchCreate(CreateView):
  model = Finch
  fields = '__all__'
  success_url = '/finches/'

class FinchUpdate(UpdateView):
  model = Finch
  fields = ['description', 'lifespan']
  success_url = '/finches/'


class FinchDelete(DeleteView):
  model = Finch
  success_url = '/finches/'

finchcollector/main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<h1>About the Finch Collector</h1>
<hr />
<p>Hire the Finch Collector!</p>

{% endblock %}

finchcollector/main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Finch Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="/" class="left brand-logo">&nbsp;&nbsp;Finch Collector</a></li>
        </ul>
        <ul class="right">
          <li><a href="/about">About</a></li>
          <li><a href="{% url 'finches_create' %}">Add a Finch</a></li>
          <li><a href="/finches">View All Finches</a></li>
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2021 Finch Collector &nbsp;</div>
  </footer>
</body>
</html>

finchcollector/main_app/templates/finches/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Finch Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ finch.name }}</span>
            <p>Breed: {{ finch.breed }}</p>
            <p>Description: {{ finch.description }}</p>
            <p>Lifespan: {{ finch.lifespan }}</p>
        </div>
        <div class="card-action">
            <a href="{% url 'finches_update' finch.id %}">Edit</a>
            <a href="{% url 'finches_delete' finch.id %}">Delete</a>
        </div>
        {% for photo in finch.photo_set.all %}
          <img class="responsive-img card-panel" src="{{photo.url}}">
        {% empty %}
          <div class="card-panel teal-text center-align">No Photos Uploaded</div>
        {% endfor %}
        <form enctype="multipart/form-data" method="POST" class="card-panel">
          {% csrf_token %}
          <input type="file" name="photo-file">
          <br><br>
          <input type="submit" class="btn" value="Upload Photo">
        </form>
    </div>
  </div>
  <div class="col s6">
    <form method="post" action="{% url 'add_feeding' finch.id %}">
      {% csrf_token %}
      {{feeding_form.as_p}}
      <input type="submit" class="btn" value="Add Feeding">
    </form>
    <table class="striped">
      <thead>
        <tr><th>Date</th><th>Meal</th></tr>
      </thead>
      <tbody>
        {% for feeding in finch.feeding_set.all %}
          <tr>
            <td>{{feeding.date}}</td>
            <td>{{feeding.get_meal_display}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
<hr>
<div class="row">
  <div class="col s6">
    <h3>{{ finch.name }}'s Toys</h3>
    {% if finch.toys.count %}
      {% for toy in finch.toys.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              A <span style="color: {{ toy.color }}">{{ toy.color }}</span> {{ toy.name }}
            </span>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>No Toys :(</h5>
    {% endif %}
  </div>
  <div class="col s6">
    <h3>Available Toys</h3>
    {% if toys.count %}
      {% for toy in toys.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              A <span style="color: {{ toy.color }}">{{ toy.color }}</span> {{ toy.name }}
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'assoc_toy' finch.id toy.id %}" method="post">
              {% csrf_token %}
              <button type="submit" class="btn">Add</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>{{finch.name}} Already Has All Toys Available</h5>
    {% endif %}
  </div>
</div>
<script>
    const dateEl = document.getElementById('id_date');
    M.Datepicker.init(dateEl, {
      format: 'yyyy-mm-dd',
      defaultDate: new Date(),
      setDefaultDate: true,
      autoClose: true
    });
  
    const selectEl = document.getElementById('id_meal');
    M.FormSelect.init(selectEl);
  </script>
  
{% endblock %}

finchcollector/main_app/templates/finches/index.html
{% extends 'base.html' %}
{% block content %}
<h1>All Finches</h1>
{% for data in finches %}
  <div class="card">
    <div class="card-content">
      <span class="card-title">{{ data.name }}</span>
      <p>Description: {{ data.description }}</p>     
      <p>Lifespan: {{ data.lifespan }}</p>
    </div>
  </div>
{% endfor %}
{% endblock %}

finchcollector/main_app/templates/main_app/finch_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Finch</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
  </form>
  <a href="{% url 'detail' finch.id %}">Cancel</a>
{% endblock %}

finchcollector/main_app/templates/main_app/finch_form.html
{% extends 'base.html' %}

{% block content %}
{% if object %}
<h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
<h1>Add Finch</h1>
{% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}